apiVersion: apps/v1beta1
kind: Deployment
metadata:
   name: nginx-deployment
spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: nginx 
     spec:
       hostNetwork: true
       containers:
         - name: nginx
           image: nginx:1.13
           ports:
             - containerPort: 80

